version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/urls-checker
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    depends_on:
      - db
    ports:
      - "8000:8000"
