# Generated by Django 3.0.2 on 2020-01-23 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UrlsChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.IntegerField(choices=[(3000, '3 second'), (5000, '5 seconds'), (10000, '10 seconds')], default=3000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
                ('links', models.ManyToManyField(related_name='links', to='checker.Link')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
